### ISSUE TITLE
markdown und Listen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#639] opened 2016-07-23 11:24 UTC
[In diesem Beitrag](https://forum.selfhtml.org/m1671766) wird in das vorletzte li-Element ein p hineingerendert. Erwartet werden (zumindest von mir) zwei Listen.

**Comment by CountOrlok** [comment] 2017-02-16 17:05
You're right. I was able to reproduce the bug. Two lists separated only by newlines cause a paragraph to be inserted into the last item of the preceeding list.

Even worse, if you mark newline separated parts of text and use the button to insert the list syntax, the replaced text will always start with two newlines, even if they're not required.

So, supposed you want to markup a long list in multiple steps using the button, this would cause the list to be split, and in addition, the undesired behavior initially described would occur.

Maybe I can fix this, but first I need to take a closer look.

**Comment by MatthiasApsel** [comment] 2017-02-16 17:44
Laut Spezifikation ist das aber gewolltes Verhalten. Siehe https://forum.selfhtml.org/meta/2017/jan/31/nummerierung-mit-zwischenabsaetzen-wie-geht-das/1685893#m1685893 und  http://spec.commonmark.org/0.26/#example-267 sowie http://spec.commonmark.org/0.26/#example-269

**Comment by CountOrlok** [comment] 2017-02-16 18:26
Ok, it seems to work as intended. According to the spec, you have to either insert a comment or change the bullet to create a new list.

However, to insert leading newlines regardless of whether they're required or not doesn't seem right.

**Comment by ckruse** [comment] 2017-02-17 14:24
Fixed by @CountOrlok

**Closed by ckruse** 2017-02-17 14:24 UTC
